<?php
// GOOGLE OAUTH CONFIGURATION
// REPLACE THESE WITH YOUR OWN GOOGLE CONSOLE PROJECT CREDENTIALS
define('GOOGLE_CLIENT_ID', 'YOUR_GOOGLE_CLIENT_ID_HERE');
define('GOOGLE_CLIENT_SECRET', 'YOUR_GOOGLE_CLIENT_SECRET_HERE');
define('GOOGLE_REDIRECT_URL', 'YOUR_GOOGLE_REDIRECT_URL_HERE');

// Scopes required for Gmail sending
define('GOOGLE_SCOPES', 'https://www.googleapis.com/auth/gmail.send');
?>
